### PR TITLE
build: remove unused platform support

### PR DESCRIPTION
**Pull request by adam-sroka**
This PR removes support for unused platforms.

Currently I just deleted the `ios` folder and removed it from version control, as none of us are actually building Gibsonify for iOS. I was thinking of doing the same for `macos` and `web`, but since we use these versions in the development process, even though we could have them locally and not checked into version control, if we needed to hard reset from origin at some point, we could lose some local configuration, so I decided to not delete these. If we wanted to disable support for them in the future, [this](https://www.kindacode.com/article/how-to-disable-web-and-desktop-support-in-flutter/) outlines the steps.

### CODE REVIEW

**Review by sshazril — APPROVED** [review]
Looks good - am for trying to remove macos and web support too

**Comment by adam-sroka** [comment]
> Looks good - am for trying to remove macos and web support too

@sshazril would you suggest I remove both macos and web in this PR too?

**Comment by sshazril** [comment]
> > Looks good - am for trying to remove macos and web support too
> 
> @sshazril would you suggest I remove both macos and web in this PR too?

I'd say it's not a priority with the other things we have on the to-do list but you're welcome to if you'd like.

**Comment by adam-sroka** [comment]
> > > Looks good - am for trying to remove macos and web support too
> > 
> > 
> > @sshazril would you suggest I remove both macos and web in this PR too?
> 
> I'd say it's not a priority with the other things we have on the to-do list but you're welcome to if you'd like.

Done 😊

**Pull request merged**
